/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.jamieburns;

import static org.testng.Assert.*;

public class LibraryTest {
    @org.testng.annotations.Test 
    public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
